apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8030
    targetPort: 8080
    nodePort: 31367
    protocol: TCP
  selector:
    app: spring-boot-app
